<?php

namespace Effectra\Http\Server;

use Effectra\Http\Message\Response;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Class RequestHandler
 *
 * Handles an HTTP request by processing a stack of middlewares.
 */
class RequestHandler implements RequestHandlerInterface
{
    /**
     * @var array The stack of middlewares.
     */
    private $stack = [];

    /**
     * RequestHandler constructor.
     *
     * @param array $stack The stack of middlewares.
     */
    public function __construct(array $stack)
    {
        $this->stack = $stack;
    }

    /**
     * Handles the server request by processing the middlewares stack.
     *
     * @param ServerRequestInterface $request The server request to handle.
     * @return ResponseInterface The response generated by the middlewares stack.
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        if (count($this->stack) > 0) {
            $middleware = array_shift($this->stack);
            return $middleware->process($request, $this);
        }

        return new Response();
    }
}